[tool.poetry]
name = "kor"
version = "0.1.0"
description = "Extract information with LLMs from text"
authors = ["Eugene Yurtsev <eyurtsev@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://www.github.com/eyurtsev/kor"


[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.6.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
black = { version="^23.1.0", extras=["black"] }
pylint = "^2.16.2"
isort = "^5.12.0"

[tool.poetry.group.docs.dependencies]
nbsphinx = "^0.8.9"
sphinx = "^4.5.0"
sphinx-autobuild = "^2021.3.14"
sphinx_book_theme = "^0.3.3"
sphinx_rtd_theme = "^1.0.0"
sphinx-typlog-theme = "^0.8.0"
sphinx-panels = "^0.6.0"
myst-nb = "^0.17.1"
linkchecker = "^10.2.1"
toml = "^0.10.2"
sphinx-copybutton = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
